site_name: "Hopsworks Documentation"
site_description: "Official documentation for Hopsworks and its Feature Store - an open source data-intensive AI platform used for the development and operation of machine learning models at scale."
site_author: "Logical Clocks"
site_url: "https://docs.hopsworks.ai/machine-learning-api/latest"

# Repository
repo_name: logicalclocks/hopsworks
repo_url: https://github.com/logicalclocks/hopsworks
edit_uri: ""

nav:
  - Feature Store: https://docs.hopsworks.ai/feature-store-api/latest/
  - Model Management:
      - Introduction: index.md
      - Integrations:
          - Overview: integrations/setup.md
          - Python: integrations/python.md
      - Model Registry:
          - Quickstart: model-registry/quickstart.md
          - Guides:
              - Project/Connection: generated/registry/project.md
              - Model Registry: generated/registry/model_registry.md
              - Model: generated/registry/model.md
              - Model Schema: generated/registry/model_schema.md
          - API Reference:
              - Connection: generated/registry/connection_api.md
              - Model Registry: generated/registry/model_registry_api.md
              - Model: generated/registry/model_api.md
              - Model Schema: generated/registry/model_schema_api.md
      - Model Serving:
          - Quickstart: model-serving/quickstart.md
          - Guides:
              - Project/Connection: generated/serving/project.md
              - Model Serving: generated/serving/model_serving.md
              # - Deployment: generated/deployment.md
              # - Predictor: generated/predictor.md
              # - Predictor configuration: generated/predictor_config.md
              # - Transformer configuration: generated/transformer_config.md
              # - Resources configuration: generated/predictor_resources_config.md
              # - Inference logger: generated/inference_logger_config.md
              # - Kafka topic: generated/kafka_topic_config.md
              # - Inference batcher: generated/inference_batcher_config.md
          - API Reference:
              - Connection: generated/serving/connection_api.md
              - Model Serving: generated/serving/model_serving_api.md
      - Contributing: CONTRIBUTING.md
  - Compute Management: https://docs.hopsworks.ai/hopsworks/latest/compute/
  - Administration: https://docs.hopsworks.ai/hopsworks/latest/admin/
  - Hopsworks.ai: https://docs.hopsworks.ai/hopsworks-cloud/latest/
  - Examples: https://examples.hopsworks.ai/
  - Community: https://community.hopsworks.ai/
  - Old Documentation: https://hopsworks.readthedocs.io/en/stable/index.html

theme:
  name: material
  favicon: assets/images/favicon.ico
  logo: assets/images/hops-logo.png
  icon:
    repo: fontawesome/brands/github
  font:
    text: "Roboto"
    code: "IBM Plex Mono"
  palette:
    accent: teal
  features:
    - navigation.tabs
    - navigation.tabs.sticky

extra:
  analytics:
    provider: google
    property: G-64FEEXPSDN
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/logicalclocks
    - icon: fontawesome/brands/github
      link: https://github.com/logicalclocks/hopsworks
    - icon: fontawesome/brands/discourse
      link: https://community.hopsworks.ai/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/logicalclocks/

extra_css:
  - css/custom.css
  - css/version-select.css

extra_javascript:
  - js/version-select.js

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - toc:
      permalink: "#"
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown_include.include:
      base_path: docs
